name: Deploy MkDocs

on:
  push:
    branches:
      - main # 源码分支，构建后推送到 gh-pages

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: first checkout
        uses: actions/checkout@v4

      - name: Configure Git user
        run: |
          git config user.name "smile-jay-lee"
          git config user.email "748974300@qq.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs deps
        run: |
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin

      - name: Build & Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force --clean -b gh-pages
